#!/bin/bash
# Stitch the four Wan clips into one cut, then export the three delivery formats.
#
# Each clip is 81 frames @16fps = 5.0625s. Crossfades overlap 0.4s, so each xfade
# offset is the running length so far minus the fades already spent.
#
# Clips are regenerated by apps/landing/blender/../video/README.md's workflow —
# see that file for the prompts and the ComfyUI graph.
set -e
cd "$(dirname "$0")"
C=clips
D=0.4
O1=4.6625      # 5.0625 - 0.4
O2=9.3250      # 5.0625*2 - 0.4*2
O3=13.9875     # 5.0625*3 - 0.4*3

ffmpeg -y -loglevel error \
  -i $C/clip1_stumped_00001_.mp4 \
  -i $C/clip2_phone_00001_.mp4 \
  -i $C/clip3b_reading_00001_.mp4 \
  -i $C/clip4b_relief_00001_.mp4 \
  -filter_complex "\
[0][1]xfade=transition=fade:duration=$D:offset=$O1[a];\
[a][2]xfade=transition=fade:duration=$D:offset=$O2[b];\
[b][3]xfade=transition=fade:duration=$D:offset=$O3[c];\
[c]minterpolate=fps=30:mi_mode=mci:mc_mode=aobmc:vsbmc=1,format=yuv420p[v]" \
  -map "[v]" -c:v libx264 -crf 18 -preset slow master.mp4

# 16:9 is the master. Square and vertical are centre crops shifted right, because
# the man sits left of centre and a plain centre crop would clip him.
ffmpeg -y -loglevel error -i master.mp4 \
  -vf "crop=720:720:280:0" \
  -c:v libx264 -crf 19 -preset slow -pix_fmt yuv420p square.mp4

ffmpeg -y -loglevel error -i master.mp4 \
  -vf "crop=405:720:340:0,scale=720:1280:flags=lanczos" \
  -c:v libx264 -crf 19 -preset slow -pix_fmt yuv420p vertical.mp4

for f in master square vertical; do
  printf "%-10s %-14s %6s  %s\n" "$f" \
    "$(ffprobe -v error -show_entries stream=width,height -of csv=p=0:s=x "$f.mp4")" \
    "$(du -h "$f.mp4" | cut -f1)" \
    "$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$f.mp4")s"
done
